########################################################
# Meta
########################################################
service: imgproc
frameworkVersion: '2'
provider:
    name: aws
    runtime: nodejs12.x

########################################################
# Functions
########################################################
functions:
    hello:
        handler: handler.hello
        events:
            - http: GET hello

########################################################
# Plugins
########################################################
plugins:
    - serverless-offline
